### ISSUE TITLE
Won't allow adding courses to a semester unlisted w/ the course. Won't allow hour changes on chosen courses.

### ISSUE THREAD

**Issue by WTremml** [alexgerstein/dartmouth-major-planner#45]
The website comes back with a "Check internet connection" error message whenever I attempt to do these things.

**Comment by alexgerstein** [comment]
Thanks for your patience while I've been improving the site. I really appreciate the bug report! The issue should be resolved now. Please let me know if you come across any other issues with the site or any other suggestions.
